### ISSUE TITLE
No audio device in blender built with system audaspace

### ISSUE THREAD

**Issue by plater** [audaspace/audaspace#10] opened 2017-09-18 09:16 UTC
See https://bugzilla.opensuse.org/show_bug.cgi?id=1057965
Seems that there is no way to select an audio device in blender built with system audaspace, this is in blender-2.79 built with audaspace-1.3.0. If blender is started with -setaudio SDL OPENAL or JACK it segfaults. I've attached the supplied gdb backtrace.
[gdb.txt](https://github.com/audaspace/audaspace/files/1310194/gdb.txt)
generated from blender -setaudio OPENAL
I'm unable to help much as I have to run blender in a VM due to the python >= 3.5 requirement and my VM is currently broken.

**Comment by neXyon** [comment] 2017-09-18 15:08
First of all this shouldn't crash. If the list of available devices only contains "None" then something went wrong when loading the plugins, are they properly installed in the location that has been configured when building audaspace?

Looking at the gdb backtrace there is an entry in the m_factories unordered_map:

["OPENAL"] = std::shared_ptr (empty) 0x0

which clearly causes the error. How it ended up there, however, is out of my imagination. If you look at the OpenALDevice::registerPlugin() method, it register's with the string "OpenAL" and the pointer should never be 0. The string "OPENAL" doesn't even exist in the whole source code of audaspace.

In any case I cannot reproduce this bug, everything works fine here. With system audaspace, you actually have to use the name shown in the user preferences of blender, which is OpenAL not OPENAL in this case. In case the name is wrong the system should not crash however, it just has no audio, since then by default the Null device is used.

So what can we do? Please check if the plugins are built and installed correctly, as long as the devices don't show up in the user settings the command line parameter won't work as well. If nothing helps, you could also try some different names like -setaudio FOOBAR and check if FOOBAR ends up in the gdb stack trace. This would freak me out, how it got there.

**Comment by plater** [comment] 2017-09-18 16:10
I've installed the plugins into the versioned arch dependent lib dir as is specified for openSUSE, we're not allowed to put libraries anywhere else 
 specified by -DDEFAULT_PLUGIN_PATH:STRING="/usr/lib64/audaspace/plugins" but I see that it defaults to /usr/local/share/audaspace/plugins when I execute cmake -L.
Could this be causing a problem? 
BTW taken from blender --help 
"-setaudio 
        Force sound system to a specific device
        NULL SDL OPENAL JACK"
which is where the " OPENAL" came from.

**Comment by neXyon** [comment] 2017-09-19 16:09
No, this is setting the path correctly, the default shouldn't matter. If the plugins are there in the path they should also be loaded properly. Of course the plugins are dynamically linked to the respective libraries, so they have to be installed as well, eg. SDL needs to be installed for the SDL plugin to work.

The stack trace still makes no sense to me and I fear without being able to reproduce the error, there isn't much I can do. Can you debug the program? Have a breakpoint in the PluginManager::loadPlugin method for example and see if everything gets loaded properly.

The help of course shows the values for the old audaspace version, since it is still used for the official release.

**Comment by plater** [comment] 2017-09-20 05:51
I suspect the problem is that blender needs to require the plugins which are in a separate package. My fault.

**Comment by neXyon** [comment] 2017-09-20 10:19
Ok, no problem. Let me know if it works with the plugins installed so that I can close the issue.

**Comment by plater** [comment] 2017-09-21 04:11
I've reproduced this segfault, without the plugin package blender shows no audio devices, with the plugins it only shows null audio device. Starting it with -setaudio OpenAL it segfaults, I will attempt to debug it later today. You can see the build log for audaspace at
https://build.opensuse.org/build/home:plater:blender/Leap_42.3/x86_64/audaspace/_log

**Comment by plater** [comment] 2017-09-22 07:22
The problem is caused by missing sym links in the plugin directory. The standard way is to package the libxxx.so symlink is in the devel package which is used for other programs to build against i.e -laudjack will link with libaudjack.so.1.3 via the .so symlink. It's unusual to find plugins with versioned suffixes and unusual to find a program that loads the plugins via their symlinks. This isn't the linux standard. 
As a work around I'm going to delete the symlinks and remove the version suffixes after they have been installed in the packaging process. The normal way of handling versioned plugins is to place them in a versioned sub directory ie.
/usr/lib64/audaspace/plugins/1.3/libaudsdl.so or /usr/lib64/audaspace-1.3/plugins/libaudsdl.so
It's your choice to fix this in a way you see fit. /usr/lib64 is $libdir and differs from distribution to distribution. openSUSE chooses to use versioned 64 bit and plain lib for 32 bit. It's the plugin directory below $libdir that needs to be versioned if audaspace is to be used by other applications besides blender otherwise simply drop the suffix and the plugins will be replaced by the newer version on update.

**Comment by plater** [comment] 2017-09-22 09:14
Unfortunately blender only sees the plugins in $libdir/audaspace/plugins, if I add -1.3 to audaspace blender doesn't see the plugins. I've reverted to packaging the sym links in the plugins package.

**Comment by neXyon** [comment] 2017-09-29 15:14
Hi Dave! Sorry for the late response, I've been very busy the last week.

Are you sure this doesn't work? If you correctly set -DDEFAULT_PLUGIN_PATH:STRING="/usr/lib64/audaspace-1.3/plugins" then this should be the path that it checks for plugins.

Also: audaspace first tries to load the plugin with name *.so.1.3 if that fails, it tries *.so so as long as one of these two is present (no matter if it's a symlink or not) it should work, so the implementation is very conservative in terms of how the files are named.

**Comment by plater** [comment] 2017-09-30 15:02
No blender doesn't even show audio in user preferences unless both the versioned libs and the .so symlinks are present. The versioned plugin directory most probably didn't work because I didn't build with the directory renamed, I renamed it manually as a test.
There's definitely something that's looking for libplugin.so and something that's looking for libplugin.so.1.3. 
I've just moved the symlinks into the plugin package as a work around but the build service check doesn't like symlinks in a non devel package.

**Comment by neXyon** [comment] 2017-10-02 15:36
Hi Dave! I just figured, that the *.so.1.3 file is only checked if the *.so file exists. My suggestion would be to do the following:

With cmake set -DDEFAULT_PLUGIN_PATH:STRING="/usr/lib64/audaspace-1.3/plugins" when building.

Then afterwards you can delete the symlinks and rename the actual libraries to *.so. This should be according to your policy and work with audaspace as well. Let me know the outcome of this please!

**Comment by plater** [comment] 2017-10-02 16:09
No audio devices except NULL in blender and if I make versioned symlinks ie libplugin.so.1.3 there's still no audio devices.

**Comment by neXyon** [comment] 2017-10-16 07:47
Hi Dave, what's the easiest way that I can give this a try myself? Is there a development virtual machine that I can download somewhere?

**Comment by plater** [comment] 2017-10-16 08:19
The virtual box Leap:42.2 vmdk I use for blender is 16G, I don't have the bandwidth to upload this. I'll try and create a workable live image with SUSE studio. I tried a vmdk image from studio a while back but could never get it to boot into X. The openSUSE build service has an image creating facility but my knowledge of the system it uses is lacking. I'll post you a link if I get a usable image for you to download, they're normally about 500M

**Comment by plater** [comment] 2017-10-16 08:38
Just a thought, I installed from the normal openSUSE:Leap iso into virtual box, using the XFCE desktop then updated python, installed blender and audaspace all from my home:plater:blender repository. You can use this method by adding the repository via "zypper ar http://download.opensuse.org/repositories/home:/plater:/blender/Leap_42.3 blender" and then "zypper dup -r blender". Installing the debug packages afterwards.

**Comment by neXyon** [comment] 2017-10-17 14:50
Hi Dave, I now installed a VM with Leap and ran those two commands and installed blender. Everything works fine in the VM - blender shows all audio devices and the plugins are located in /usr/lib64/audaspace-1.3/plugins with symlinks and sonumbers removed. Isn't that what you wanted to work?

**Comment by plater** [comment] 2017-10-18 06:31
I'm making a fresh install, the only thing that may be different with my installation is a newer SDL version which I removed from the home:plater:blender repository.

**Comment by plater** [comment] 2017-10-18 07:47
Yes all the audio devices are present, I suspect that the blender in my old vm wasn't built against the new audaspace. Could this have been the cause?

**Comment by neXyon** [comment] 2017-10-18 07:52
I'm not sure what caused the problem here. If it is dynamically linked and the old version not loaded somehow accidentally (by being sure it's uninstalled for example), that shouldn't be it. But I'm happy to hear everything is working now. I'll close this issue. If you have any more questions/problems, feel free to reopen or open another issue.

**Closed by neXyon** 2017-10-18 07:52 UTC

**Comment by plater** [comment] 2017-10-18 08:52
Are you going to remove the symlinks from the build? I use a bash for loop to remove the version suffixes in the install stage at the moment.

**Comment by neXyon** [comment] 2017-10-23 14:40
Hi Dave,

I added a build option with d27746c: WITH_VERSIONED_PLUGINS

Cheers,
Jörg

**Comment by plater** [comment] 2017-10-23 15:17
Thanks
